const filmsSeed = [
    {
        id: 1,
        title: "Keep Moving Forward",
        author: "Rocky Balboa (Actor: Sylvestor Stallone)",
        genre: "Films",
        synopsis: "[Robert]: So you nervous about the fight? Scared to death? [Rocky]: Scared to death [Robert]:You don’t look scared. [Rocky]: Well, I ain’t supposed to. [Robert]: Then you don’t have to do it. [Rocky]: Yeah, well, I think I do. [Robert]: You know, living with you, it hasn’t been easy. People see me but they think of you. Now, with all this going on, it’s gonna be worse than ever. [Rocky]: It doesn’t have to be. [Robert]: Sure it does! [Rocky]: Why? You’ve got a lot going on, kid. [Robert]: What, my last name? That’s the reason I got a decent job. That’s the reason why people deal with me in the first place. Now I start to get a little ahead. I start to get a little something for myself, and this happens. Now, I’m asking you as a favor not to go through with this, okay. This is gonna end up bad for you, and it’s gonna end up bad for me. [Rocky]: You think I’m hurting you? [Robert]: Yeah, in a way, you are. [Rocky]: That’s the last thing I ever wanted to do. [Robert]: I know that’s not what you wanna do, but that’s just the way that it is. Don’t you care what people think? Doesn’t bother you that people…are making you out to be joke and that I’ll be included in that? Do you think that’s right? Do you? [Rocky]: You ain’t gonna believe this, but you used to fit right here. I’d hold you up to say to your mother, “This kid’s gonna be the best kid in the world. This kid’s gonna be somebody better than anybody I ever knew.” And you grew up good and wonderful. It was great just watching you, every day was like a privilege. Then the time come for you to be your own man and take on the world, and you did. But somewhere along the line, you changed. You stopped being you. You let people stick a finger in your face and tell you you’re no good. And when things got hard, you started looking for something to blame, like a big shadow. Let me tell you something you already know. The world ain’t all sunshine and rainbows. It’s a very mean and nasty place and I don’t care how tough you are it will beat you to your knees and keep you there permanently if you let it. You, me, or nobody is gonna hit as hard as life. But it ain’t about how hard ya hit. It’s about how hard you can get hit and keep moving forward. How much you can take and keep moving forward. That’s how winning is done! Now if you know what you’re worth then go out and get what you’re worth. But ya gotta be willing to take the hits, and not pointing fingers saying you ain’t where you wanna be because of him, or her, or anybody! Cowards do that and that ain’t you! You’re better than that! I’m always gonna love you no matter what. No matter what happens. You’re my son and you’re my blood. You’re the best thing in my life. But until you start believing in yourself, ya ain’t gonna have a life. Don’t forget to visit your mother.",
    },
    {
        id: 2,
        title: "What Every Boy Needs to Know About Being a Man",
        author: "Hub McCann (Actor: Robert Duvall)",
        genre: "Films",
        synopsis:
            "If you want to believe in something, believe in it. Just because something isn't true doesn't mean you can't believe in it. Sometimes the things that may or may not be true are the things a man needs to believe in the most: That people are basically good. That courage, honor and virtue mean everything. That power and money, money and power mean nothing. That good always triumphs over evil. And I want you to remember this; That love,true love, Never dies. You remember that boy, remember that. Whether they're true or not those are the things a man should believe in because those are the things worth believing IN. Got that?",
    }
]

module.exports = filmsSeed;